version: '3.8'
services:
  mysql:
    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: SANdatabase7$$
      MYSQL_DATABASE: orders_db
      MYSQL_USER: root
      MYSQL_PASSWORD: SANdatabase7$$

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "3009:3009"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: SANdatabase7$$
      DB_NAME: orders_db 

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
